apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops7
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mlops7
  template:
    metadata:
      labels:
        app: mlops7
    spec:
      containers:
      - name: mlops7
        image: us-central1-docker.pkg.dev/lofty-voyage-461011-f1/mlops7/mlops7_image:latest
        
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mlops-service
spec:
  selector:
    app: mlops7
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer